"""init

Revision ID: 0c847d9a1155
Revises: 
Create Date: 2025-07-18 16:00:37.630053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c847d9a1155'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'PROCESSING', 'FINISHED', 'PENDING', name='status'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('input_file_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_file_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itemcode', sa.String(), nullable=False),
    sa.Column('jobid', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'PROCESSING', 'FINISHED', 'PENDING', name='status'), nullable=False),
    sa.Column('urls', sa.String(), nullable=True),
    sa.Column('scraped_data', sa.String(), nullable=True),
    sa.Column('extracted_sections', sa.String(), nullable=True),
    sa.Column('openai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobid'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('jobs')
    # ### end Alembic commands ###
